In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


##introduction to tensors
creating tensors





In [ ]:
#scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2],
                         [3,6],
                         [2,4]]])
TENSOR

tensor([[[1, 2],
         [3, 6],
         [2, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

##Random tensors

why random tensors



In [ ]:
#create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0663, 0.6801, 0.5552, 0.6086],
        [0.8966, 0.7664, 0.3492, 0.5449],
        [0.6247, 0.3810, 0.4650, 0.0540]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colorchenal
random_image_size_tensor.shape,random_image_size_tensor .ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensors = torch.rand(2,4,3)
random_tensors

tensor([[[0.8457, 0.2074, 0.3219],
         [0.1194, 0.1804, 0.3760],
         [0.4538, 0.0427, 0.1265],
         [0.6803, 0.0176, 0.6956]],

        [[0.0689, 0.6780, 0.6652],
         [0.4014, 0.5029, 0.9847],
         [0.7922, 0.1499, 0.7121],
         [0.1061, 0.5043, 0.6414]]])

In [ ]:
#create a tensor of all zeors
zero =torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])